export const randomCars: string[] = [
  'Honda Civic',
  'Ford Focus',
  'Toyota Corolla',
  'Chevrolet Malibu',
  'Nissan Altima',
  'BMW 3 Series',
  'Audi A4',
  'Mercedes-Benz C-Class',
  'Volkswagen Jetta',
  'Hyundai Elantra',
  'Kia Forte',
  'Subaru Impreza',
  'Mazda Mazda3',
  'Lexus IS',
  'Infiniti Q50',
  'Cadillac ATS',
  'Lincoln MKZ',
  'Buick Regal',
  'Acura ILX',
  'Genesis G70',
  'Tesla Model 3',
  'Chevrolet Cruze',
  'Ford Fusion',
  'Honda Accord',
  'Toyota Camry',
  'Nissan Sentra',
  'BMW 5 Series',
  'Audi A6',
  'Mercedes-Benz E-Class',
  'Volkswagen Passat',
  'Hyundai Sonata',
  'Kia Optima',
  'Subaru Legacy',
  'Mazda Mazda6',
  'Lexus ES',
  'Infiniti Q60',
  'Cadillac CTS',
  'Lincoln Continental',
  'Buick LaCrosse',
  'Acura TLX',
  'Genesis G80',
  'Chevrolet Impala',
  'Ford Taurus',
  'Honda Insight',
  'Toyota Avalon',
  'Nissan Maxima',
  'BMW 7 Series',
  'Audi A8',
  'Mercedes-Benz S-Class',
  'Volkswagen Arteon',
  'Hyundai Azera',
  'Kia Cadenza',
  'Subaru Ascent',
  'Mazda CX-9',
  'Lexus LS',
  'Infiniti QX50',
  'Cadillac XT5',
  'Lincoln Aviator',
  'Buick Enclave',
  'Acura MDX',
  'Genesis GV80',
  'Chevrolet Traverse',
  'Ford Explorer',
  'Honda Pilot',
  'Toyota Highlander',
  'Nissan Pathfinder',
  'BMW X3',
  'Audi Q5',
  'Mercedes-Benz GLC',
  'Volkswagen Tiguan',
  'Hyundai Santa Fe',
  'Kia Sorento',
  'Subaru Outback',
  'Mazda CX-5',
  'Lexus RX',
  'Infiniti QX60',
  'Cadillac XT6',
  'Lincoln Nautilus',
  'Buick Encore',
  'Acura RDX',
  'Genesis GV70',
  'Chevrolet Equinox',
  'Ford Escape',
  'Honda CR-V',
  'Toyota RAV4',
  'Nissan Rogue',
  'BMW X5',
  'Audi Q7',
  'Mercedes-Benz GLE',
  'Volkswagen Atlas',
  'Hyundai Tucson',
  'Kia Sportage',
  'Subaru Forester',
  'Mazda CX-30',
  'Lexus NX',
  'Infiniti QX80',
  'Cadillac Escalade',
  'Lincoln Navigator',
  'Buick Envision',
  'Acura MDX',
  'Genesis GV80',
  'Chevrolet Tahoe',
  'Ford Expedition',
  'Honda Passport',
  'Toyota Sequoia',
  'Nissan Armada',
  'BMW X7',
  'Audi Q8',
  'Mercedes-Benz GLS',
  'Volkswagen Touareg',
  'Hyundai Palisade',
  'Kia Telluride',
  'Subaru Ascent',
  'Mazda CX-9',
  'Lexus LX',
  'Infiniti QX60',
  'Cadillac Escalade ESV',
  'Lincoln Navigator L',
  'Buick Enclave',
  'Acura MDX',
  'Genesis GV80',
  'Chevrolet Suburban',
  'Ford Expedition Max',
  'Honda Pilot',
  'Toyota Land Cruiser',
  'Nissan Armada',
  'BMW X7',
  'Audi Q8',
  'Mercedes-Benz GLS',
  'Volkswagen Atlas Cross Sport',
  'Hyundai Palisade',
  'Kia Telluride',
  'Subaru Ascent',
  'Mazda CX-9',
  'Lexus GX',
  'Infiniti QX80',
  'Cadillac Escalade ESV',
  'Lincoln Navigator L',
  'Buick Enclave',
  'Acura MDX',
  'Genesis GV80',
  'Chevrolet Tahoe',
  'Ford Expedition',
  'Honda Pilot',
  'Toyota Sequoia',
  'Nissan Armada',
  'BMW X7',
  'Audi Q8',
  'Mercedes-Benz GLS',
  'Volkswagen Touareg',
  'Hyundai Palisade',
  'Kia Telluride',
  'Subaru Ascent',
  'Mazda CX-9',
  'Lexus LX',
  'Infiniti QX60',
  'Cadillac Escalade ESV',
  'Lincoln Navigator L',
  'Buick Enclave',
  'Toyota Yaris',
  'Volkswagen Golf',
  'Ford Fiesta',
  'Chevrolet Sonic',
  'Hyundai Accent',
  'Nissan Versa',
  'Honda Fit',
  'Kia Rio',
  'Mazda Mazda2',
  'Subaru Crosstrek',
  'Lexus CT',
  'Acura RLX',
  'Genesis G90',
  'Tesla Model S',
  'Chevrolet Bolt EV',
  'Nissan Leaf',
  'BMW i3',
  'Jaguar I-PACE',
  'Audi e-tron',
  'Mercedes-Benz EQC',
  'Porsche Taycan',
  'Kia Soul EV',
  'Hyundai Kona Electric',
  'Volkswagen ID.4',
  'Ford Mustang Mach-E',
  'Toyota Prius',
  'Honda Insight',
  'Hyundai Ioniq',
  'Kia Niro',
  'Lexus UX',
  'Audi A3',
  'BMW 2 Series',
  'Mercedes-Benz A-Class',
  'Volvo S60',
  'Alfa Romeo Giulia',
  'Acura ILX',
  'Genesis G70',
  'Cadillac CT4',
  'Lincoln MKZ',
  'Buick Regal',
  'Nissan Sentra',
  'Toyota Corolla',
  'Honda Civic',
  'Volkswagen Jetta',
  'Hyundai Elantra',
  'Kia Forte',
  'Mazda Mazda3',
  'Subaru Impreza',
  'Ford Focus',
  'Chevrolet Cruze',
  'BMW 3 Series',
  'Mercedes-Benz C-Class',
  'Audi A4',
  'Lexus IS',
  'Infiniti Q50',
  'Genesis G80',
  'Tesla Model 3',
  'Chevrolet Malibu',
  'Nissan Altima',
  'Toyota Camry',
  'Honda Accord',
  'Volkswagen Passat',
  'Hyundai Sonata',
  'Kia Optima',
  'Mazda Mazda6',
  'Subaru Legacy',
  'Ford Fusion',
  'BMW 5 Series',
  'Mercedes-Benz E-Class',
  'Audi A6',
  'Lexus ES',
  'Infiniti Q60',
  'Genesis G90',
  'Chevrolet Impala',
  'Lincoln Continental',
  'Cadillac CTS',
  'Buick LaCrosse',
  'Nissan Maxima',
  'Toyota Avalon',
  'Honda Insight',
  'Volkswagen Arteon',
  'Hyundai Azera',
  'Kia Cadenza',
  'Mazda MX-30',
  'Subaru Ascent',
  'Ford Explorer',
  'Chevrolet Traverse',
  'Honda Pilot',
  'Toyota Highlander',
  'Nissan Pathfinder',
  'BMW X3',
  'Audi Q5',
  'Mercedes-Benz GLC',
  'Lexus RX',
  'Infiniti QX50',
  'Genesis GV80',
  'Cadillac XT5',
  'Lincoln Aviator',
  'Buick Enclave',
  'Hyundai Palisade',
  'Kia Telluride',
  'Mazda CX-9',
  'Subaru Outback',
  'Volkswagen Tiguan',
  'Ford Escape',
  'Chevrolet Equinox',
  'Honda CR-V',
  'Toyota RAV4',
  'Nissan Rogue',
  'BMW X5',
  'Audi Q7',
  'Mercedes-Benz GLE',
  'Lexus NX',
  'Infiniti QX60',
  'Genesis GV70',
  'Cadillac XT6',
  'Lincoln Nautilus',
  'Buick Encore',
  'Hyundai Santa Fe',
  'Kia Sorento',
  'Mazda CX-5',
  'Subaru Forester',
  'Volkswagen Atlas',
  'Ford Edge',
  'Chevrolet Blazer',
  'Honda Passport',
  'Toyota Venza',
  'Nissan Murano',
  'BMW X6',
  'Audi Q8',
  'Mercedes-Benz GLS',
  'Lexus RX L',
  'Infiniti QX80',
  'Genesis GV80',
  'Cadillac Escalade',
  'Lincoln Navigator',
  'Buick Envision',
  'Hyundai Tucson',
  'Kia Sportage',
  'Mazda CX-30',
  'Subaru Crosstrek',
  'Volkswagen Taos',
  'Ford Bronco Sport',
  'Chevrolet Trailblazer',
  'Honda HR-V',
  'Toyota C-HR',
  'Nissan Kicks',
  'BMW X1',
  'Audi Q3',
  'Mercedes-Benz GLB',
  'Lexus UX',
  'Infiniti QX50',
  'Genesis GV70',
  'Cadillac XT4',
  'Lincoln Corsair',
  'Buick Encore GX',
  'Hyundai Venue',
  'Kia Seltos',
  'Mazda CX-3',
  'Subaru Crosstrek',
  'Volkswagen ID.4',
  'Ford Mustang Mach-E',
  'Chevrolet Bolt EV',
  'Nissan Leaf',
  'BMW i3',
  'Audi e-tron',
  'Mercedes-Benz EQC',
  'Volvo XC40 Recharge',
  'Porsche Taycan',
  'Kia Soul EV',
  'Hyundai Kona Electric',
  'Jaguar I-PACE'
];
